# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160923_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
