# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160923_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Coach'),
            preserve_default=False,
        ),
    ]
